version: '3'
services:
  db:
    image: postgres:13
    restart: "no"
    command:
      - "postgres"
      - "-c"
      - "search_path=public,content"

    env_file: ./postgres/.env
    volumes:
        - ./postgres/init_pg:/docker-entrypoint-initdb.d
        - postgres_data:/var/lib/postgresql/data

  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - static_volume:/code/static:ro
    depends_on:
      - django

  fastapi:
    restart: always
    build: ./fastapi-solution/src
    env_file:
      - ./fastapi-solution/api.env
    depends_on:
      - db
      - redis
      - elasticsearch

  django:
    build: ./django/ 
    restart: always
    env_file: ./django/.env
    volumes:
      - static_volume:/code/static
      - ./sqlite_to_postgres:/in_data
    depends_on:
      - db
      - redis
      - elasticsearch
  
  elasticsearch:
    restart: always
    image: elasticsearch:8.10.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms200m -Xmx200m"
    volumes:
      - esdata:/usr/share/elasticsearch/data
  
  redis:
    restart: always
    image: redis:latest
    environment:
      REDIS_USER: admin
      REDIS_PASSWORD: admin
      
  etl:
    build: ./etl
    env_file: ./etl/.env
    depends_on:
      - db
      - elasticsearch

volumes:
  static_volume:
  postgres_data:
  esdata: