# Generated by Django 3.2 on 2023-10-28 22:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_genre_name_is_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='rating',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, 'Рейтинг не может быть меньше 0'), django.core.validators.MaxValueValidator(100, 'Рейтинг  не может быть больше 100')], verbose_name='rating'),
        ),
    ]
