version: '3'
services:
  db-file:
    image: postgres:13
    restart: "no"
    command:
      - "postgres"
      - "-c"
      - "search_path=public,file_api"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U app -d fileapi_db" ]
      interval: 30s
      timeout: 10s
      retries: 5
    env_file: ./pg-db/.env
    volumes:
        - ./pg-db/init_pg:/docker-entrypoint-initdb.d
        - fileapi_db:/var/lib/postgresql/data

  api-migrations:
    build:
      context: .
    restart: no
    depends_on:
      db-file:
        condition: service_healthy
    command: alembic upgrade head

  fastapi-file:
    restart: always
    build: .
    env_file:
      - ./api.env 
      
  minio:
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=practicum
      - MINIO_ROOT_PASSWORD=StrongPass
    volumes:
      - minio_storage:/data
    command: server --console-address ":9001" /data

volumes:
  minio_storage: 
  fileapi_db:
