version: '3'
services:
  db-file:
    image: postgres:13
    restart: "no"
    command:
      - "postgres"
      - "-c"
      - "search_path=public,content"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U app -d fileapi_db" ]
      interval: 30s
      timeout: 10s
      retries: 5
    env_file: ./pg-db/.env
    volumes:
        - ./pg-db/init_pg:/docker-entrypoint-initdb.d
        - fileapi_db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  fastapi-file:
    restart: always
    build: ./api/
    env_file:
      - ./api.env
    volumes:
      - ./api/:/opt/app/
    depends_on:
      db-file:
        condition: service_healthy
      minio:
        condition: service_started
    ports:
      - "8002:8000"
      
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=practicum
      - MINIO_ROOT_PASSWORD=StrongPass
    volumes:
      - minio_storage:/data
    command: server --console-address ":9001" /data
    
volumes:
  minio_storage: 
  fileapi_db: