"""initial migration

Revision ID: f25bb935b7af
Revises:
Create Date: 2023-12-30 19:55:14.215655

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f25bb935b7af'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_properties',
                    sa.Column('path_in_storage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('size', sa.Integer(), nullable=False),
                    sa.Column('file_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('short_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    schema='file_api'
                    )
    op.create_index(op.f('ix_file_api_file_properties_path_in_storage'), 'file_properties', ['path_in_storage'],
                    unique=True, schema='file_api')
    op.create_index(op.f('ix_file_api_file_properties_short_name'), 'file_properties', ['short_name'], unique=True,
                    schema='file_api')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_api_file_properties_short_name'), table_name='file_properties', schema='file_api')
    op.drop_index(op.f('ix_file_api_file_properties_path_in_storage'), table_name='file_properties', schema='file_api')
    op.drop_table('file_properties', schema='file_api')
    # ### end Alembic commands ###
