version: '3'
services:
  api:
    restart: always
    build: ./src
    env_file:
      - api.env
    depends_on:
      - db
      - redis
      - elastic
    volumes:
      - ./src/:/opt/app/
    ports:
      - "8001:8000"
  elastic:
    restart: always
    image: elasticsearch:8.10.2
    environment:
      - xpack.security.enabled=false  
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms2048m -Xmx2048m
    ports:
      - "9200:9200"
      - "9300:9300"
  redis:
    restart: always
    image: redis:latest
    environment:
      REDIS_USER: admin
      REDIS_PASSWORD: admin
    ports:
      - 6379:6379


  